/* Generates the colour tokens. `npm run tokens`.
 *
 * Outputs
 *   src/styles/tokens.css        the three layers
 *   src/tokens/categories.ts     typed category list for app code
 *   src/styles/shadcn-bridge.css optional — points shadcn's variables at the
 *                                system. Not imported by default; adding
 *                                `@import "./styles/shadcn-bridge.css";` to
 *                                index.css switches the whole app over.
 *   tokens/figma-recipe.js       the block to paste into the Figma plugin
 *
 * Contrast guarantees are asserted here. A retune that breaks accessibility
 * fails the build instead of shipping.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  NEUTRAL, CATEGORIES, SIGNALS, semanticMap, primitives, cssName, contrast
} from "./recipe.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const write = (rel, body) => {
  const path = resolve(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
  return rel;
};

const P = primitives();
const LIGHT = semanticMap(false);
const DARK = semanticMap(true);
const BANNER = "/* Generated by tokens/build.mjs — do not edit by hand.\n   Change tokens/recipe.mjs and run `npm run tokens`. */\n";

/* ---------------------------------------------------------------- */
/* Layer 1 — primitives                                              */
/* ---------------------------------------------------------------- */

const l1 = [];
l1.push("/* ── Layer 1 · primitives ──────────────────────────────────────");
l1.push("   Raw values, derived from the recipe. Never reference these from a");
l1.push("   component — always go through the semantic layer below. */");
l1.push(":root {");
l1.push("  /* neutral ramp — cream at the top, slate at the bottom */");
NEUTRAL.steps.forEach((s) => l1.push(`  ${cssName(`neutral/${s}`)}: ${P[`neutral/${s}`]};`));
l1.push("");
l1.push("  /* categories — fill and background, per theme */");
for (const c of CATEGORIES) {
  const vals = ["fill-light", "fill-dark", "bg-light", "bg-dark"]
    .map((k) => `  ${cssName(`category/${c.name}/${k}`)}: ${P[`category/${c.name}/${k}`]};`);
  l1.push(...vals);
}
l1.push("");
l1.push("  /* signals — the only colours that become words */");
for (const s of SIGNALS) {
  for (const k of ["fill-light", "fill-dark", "bg-light", "bg-dark", "text-light", "text-dark"]) {
    l1.push(`  ${cssName(`signal/${s.name}/${k}`)}: ${P[`signal/${s.name}/${k}`]};`);
  }
}
l1.push("}");

/* ---------------------------------------------------------------- */
/* Layers 2 and 3 — semantic                                         */
/* ---------------------------------------------------------------- */

const GROUPS = [
  ["chrome — everything the app owns, no hue of its own",
    (t) => t.startsWith("surface/") || t.startsWith("border/") || t.startsWith("text/")],
  ["categories — the user's data, the loudest thing on screen",
    (t) => t.startsWith("category/")],
  ["signals — success and failure messages only, never a row chip",
    (t) => t.startsWith("signal/")]
];

function body(map, pad) {
  const out = [];
  for (const [label, test] of GROUPS) {
    out.push(`${pad}/* ${label} */`);
    for (const token of Object.keys(map).filter(test)) {
      out.push(`${pad}${cssName(token)}: var(${cssName(map[token])});`);
    }
    out.push("");
  }
  out.pop();
  return out;
}

const l2 = [
  "/* ── Layer 2 · semantic, light ─────────────────────────────────",
  "   What components use. Each one points at a primitive. */",
  ":root {",
  ...body(LIGHT, "  "),
  "}"
];

const l3 = [
  "/* ── Layer 3 · semantic, dark ──────────────────────────────────",
  "   Identical token names, remapped. Nothing else in the app changes.",
  "   Scoped to .dark to match the @custom-variant in index.css. */",
  ".dark {",
  ...body(DARK, "  "),
  "}"
];

const css = [BANNER, l1.join("\n"), "", l2.join("\n"), "", l3.join("\n"), ""].join("\n");

/* ---------------------------------------------------------------- */
/* shadcn bridge — optional                                          */
/* ---------------------------------------------------------------- */

const BRIDGE = {
  "background": "surface/ground",
  "foreground": "text/primary",
  "card": "surface/raised",
  "card-foreground": "text/primary",
  "popover": "surface/raised",
  "popover-foreground": "text/primary",
  "primary": "text/primary",
  "primary-foreground": "surface/raised",
  "secondary": "surface/sunken",
  "secondary-foreground": "text/primary",
  "muted": "surface/sunken",
  "muted-foreground": "text/muted",
  "accent": "surface/sunken",
  "accent-foreground": "text/primary",
  "destructive": "signal/danger/fill",
  "border": "border/default",
  "input": "border/default",
  "ring": "text/muted",
  "chart-1": "category/poppy/fill",
  "chart-2": "category/jade/fill",
  "chart-3": "category/azure/fill",
  "chart-4": "category/iris/fill",
  "chart-5": "category/ochre/fill",
  "sidebar": "surface/raised",
  "sidebar-foreground": "text/primary",
  "sidebar-primary": "text/primary",
  "sidebar-primary-foreground": "surface/raised",
  "sidebar-accent": "surface/sunken",
  "sidebar-accent-foreground": "text/primary",
  "sidebar-border": "border/subtle",
  "sidebar-ring": "text/muted"
};

const bridge = [
  BANNER,
  "/* Points shadcn/ui's variables at the design system, so existing",
  "   components pick it up without being touched.",
  "",
  "   NOT imported by default — this changes how every screen looks.",
  "   To switch over, add to index.css after the tokens import:",
  "",
  '     @import "./styles/shadcn-bridge.css";',
  "",
  "   Both themes come along, because the tokens resolve per theme. */",
  "",
  ":root, .dark {",
  ...Object.entries(BRIDGE).map(([k, v]) => `  --${k}: var(${cssName(v)});`),
  "}",
  ""
].join("\n");

/* ---------------------------------------------------------------- */
/* categories.ts                                                     */
/* ---------------------------------------------------------------- */

const ts = `${BANNER}
/** A category stores its id, never a colour. Retuning a hue in
 *  tokens/recipe.mjs updates every existing category automatically. */
export const CATEGORIES = ${JSON.stringify(
  CATEGORIES.map(({ id, name, hue, tier }) => ({ id, name, hue, tier })), null, 2
)} as const;

export type CategoryColor = (typeof CATEGORIES)[number];
export type CategoryColorId = CategoryColor["id"];
export type CategoryColorName = CategoryColor["name"];
export type CategoryRole = "fill" | "bg";

export const isCategoryColorId = (v: unknown): v is CategoryColorId =>
  typeof v === "number" && CATEGORIES.some((c) => c.id === v);

/** Category.color currently holds a hex string. This resolves either an id
 *  (new) or a name (also fine), and returns null for a legacy hex so callers
 *  can fall back while the data migrates. */
export function resolveCategoryColor(
  value: string | number | null | undefined
): CategoryColor | null {
  if (typeof value === "number") return CATEGORIES.find((c) => c.id === value) ?? null;
  if (typeof value === "string") return CATEGORIES.find((c) => c.name === value) ?? null;
  return null;
}

/** The bridge from stored value to painted colour. Resolves per theme
 *  automatically, because the CSS variable does. */
export function categoryVar(
  value: string | number | null | undefined,
  role: CategoryRole = "fill"
): string | null {
  const c = resolveCategoryColor(value);
  return c ? \`var(--category-\${c.name}-\${role})\` : null;
}
`;

/* ---------------------------------------------------------------- */
/* figma-recipe.js                                                   */
/* ---------------------------------------------------------------- */

const figma = `/* Paste over the NEUTRAL block AND the two neutral* functions in the
   Figma plugin's code.js. Generated from tokens/recipe.mjs.

   NOTE: the hue and chroma functions changed shape — the ramp no longer drifts
   evenly between the two hues, so replacing only the NEUTRAL object is not
   enough. Replace the functions below as well or Figma will drift from code. */

var NEUTRAL = {
  steps: [${NEUTRAL.steps.join(", ")}],
  L:     [${NEUTRAL.L.join(", ")}],
  hueLight: ${NEUTRAL.hueLight},
  hueDark: ${NEUTRAL.hueDark},
  crossStart: ${NEUTRAL.crossStart},
  crossEnd: ${NEUTRAL.crossEnd},
  chromaStops: [
${NEUTRAL.chromaStops.map((s) => `    [${s[0]}, ${s[1]}]`).join(",\n")}
  ]
};

function neutralChroma(L) {
  var s = NEUTRAL.chromaStops;
  if (L >= s[0][0]) return s[0][1];
  for (var i = 0; i < s.length - 1; i++) {
    var L1 = s[i][0], C1 = s[i][1], L2 = s[i + 1][0], C2 = s[i + 1][1];
    if (L <= L1 && L >= L2) return C1 + (C2 - C1) * ((L1 - L) / (L1 - L2));
  }
  return s[s.length - 1][1];
}

function neutralHue(L) {
  var s = Math.max(0, Math.min(1, (NEUTRAL.crossStart - L) / (NEUTRAL.crossStart - NEUTRAL.crossEnd)));
  return NEUTRAL.hueLight + (NEUTRAL.hueDark - NEUTRAL.hueLight) * (s * s * (3 - 2 * s));
}

function neutralAt(i) {
  var L = NEUTRAL.L[i], H = neutralHue(L);
  return rgba(L, Math.min(neutralChroma(L), 0.94 * maxChroma(L, H)), H);
}
`;

/* ---------------------------------------------------------------- */
/* Guarantees                                                        */
/* ---------------------------------------------------------------- */

const checks = [];
const add = (label, a, b, min) => checks.push({ label, ratio: contrast(a, b), min });

for (const [theme, map] of [["light", LIGHT], ["dark", DARK]]) {
  const v = (t) => P[map[t]];
  add(`${theme} · raised on ground`, v("surface/raised"), v("surface/ground"), 1.2);
  add(`${theme} · sunken on raised`, v("surface/sunken"), v("surface/raised"), 1.2);
  add(`${theme} · track on raised`, v("surface/track"), v("surface/raised"), 1.2);
  add(`${theme} · primary text on ground`, v("text/primary"), v("surface/ground"), 4.5);
  add(`${theme} · secondary text on raised`, v("text/secondary"), v("surface/raised"), 4.5);
  add(`${theme} · muted text on ground`, v("text/muted"), v("surface/ground"), 4.5);
  add(`${theme} · muted text on raised`, v("text/muted"), v("surface/raised"), 4.5);

  for (const c of CATEGORIES) {
    add(`${theme} · ${c.name} bar on track`, v(`category/${c.name}/fill`), v("surface/track"), 3);
    add(`${theme} · text on ${c.name} background`, v("text/primary"), v(`category/${c.name}/bg`), 4.5);
  }
  for (const s of SIGNALS) {
    add(`${theme} · ${s.role} text on ground`, v(`signal/${s.role}/text`), v("surface/ground"), 4.5);
    add(`${theme} · ${s.role} text on its background`, v(`signal/${s.role}/text`), v(`signal/${s.role}/bg`), 4.5);
  }
}

const failed = checks.filter((c) => c.ratio < c.min);

const written = [
  write("src/styles/tokens.css", css),
  write("src/styles/shadcn-bridge.css", bridge),
  write("src/tokens/categories.ts", ts),
  write("tokens/figma-recipe.js", figma)
];

for (const w of written) console.log("  wrote " + w);
console.log(`  ${checks.length - failed.length}/${checks.length} contrast checks pass`);

if (failed.length) {
  console.error("\nFAILED:");
  for (const f of failed) console.error(`  ${f.label} — ${f.ratio.toFixed(2)}, needs ${f.min}`);
  process.exit(1);
}
