/* Builds the design tokens from Figma. `npm run tokens`.
 *
 * Source
 *   tokens/figma.json   exported from Figma (plugin → Export tokens to JSON).
 *                       Figma is where design decisions are made; this file is
 *                       never edited by hand.
 *   tokens/config.mjs   the few things Figma cannot know: stable category ids,
 *                       font fallback stacks, rem base.
 *
 * Outputs
 *   src/styles/tokens.css        primitives, type, dimensions, light + dark
 *   src/tokens/categories.ts     typed category list for app code
 *   src/styles/shadcn-bridge.css optional — points shadcn's variables at the
 *                                system. Not imported by default.
 *
 * Guardrails
 *   Contrast pairs and structural checks run on every build. A Figma change
 *   that breaks accessibility, or leaves a token half-defined, fails here
 *   instead of shipping.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CATEGORY_IDS, FONTS, ROOT_SIZE, BRIDGE } from "./config.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const write = (rel, body) => {
  const path = resolve(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
  return rel;
};

const BANNER = "/* Generated by tokens/build.mjs from tokens/figma.json — do not edit by hand.\n   Change the design in Figma, re-export, and run `npm run tokens`. */\n";
const cssName = (token) => "--" + token.replace(/[\s/]+/g, "-");
const rem = (px) => +(px / ROOT_SIZE).toFixed(4) + "rem";
const slug = (s) => s.trim().toLowerCase().replace(/\s+/g, "-");

const errors = [];

/* ---------------------------------------------------------------- */
/* Read Figma                                                        */
/* ---------------------------------------------------------------- */

const FIGMA = JSON.parse(readFileSync(resolve(root, "tokens/figma.json"), "utf8"));

/* Flattens a DTCG group into { "a/b/c": token }. */
function flatten(group = {}, prefix = "", out = {}) {
  for (const [k, v] of Object.entries(group)) {
    if (k.startsWith("$") || !v || typeof v !== "object") continue;
    const path = prefix ? `${prefix}/${k}` : k;
    if ("$value" in v) out[path] = v;
    else flatten(v, path, out);
  }
  return out;
}

/* Primitives — raw hex values. */
const P = {};
for (const [k, t] of Object.entries(flatten(FIGMA["Primitives"]))) {
  const hex = String(t.$value).toLowerCase();
  if (!/^#[0-9a-f]{6}$/.test(hex)) errors.push(`primitive ${k} — "${t.$value}" is not a 6-digit hex`);
  P[k] = hex;
}

/* Semantic — each token must alias a primitive, never hold a raw value. */
function semantic(collection) {
  const map = {};
  for (const [k, t] of Object.entries(flatten(FIGMA[collection]))) {
    const m = typeof t.$value === "string" && t.$value.match(/^\{Primitives\.(.+)\}$/);
    if (!m) { errors.push(`${collection} · ${k} — "${t.$value}" is not an alias to a primitive`); continue; }
    const target = m[1].replace(/\./g, "/");
    if (!(target in P)) errors.push(`${collection} · ${k} — points at ${target}, which is not a primitive`);
    map[k] = target;
  }
  return map;
}
const LIGHT = semantic("Semantic Light");
const DARK = semantic("Semantic Dark");
for (const k of Object.keys(LIGHT)) if (!(k in DARK)) errors.push(`${k} — in Semantic Light, missing from Semantic Dark`);
for (const k of Object.keys(DARK)) if (!(k in LIGHT)) errors.push(`${k} — in Semantic Dark, missing from Semantic Light`);

/* Categories — names come from Figma, ids from config (ids are stored in
 * user data, so they must never shift when Figma's order does). */
const figmaCategories = [...new Set(Object.keys(LIGHT).filter((k) => k.startsWith("category/")).map((k) => k.split("/")[1]))];
for (const name of figmaCategories) if (!(name in CATEGORY_IDS)) errors.push(`category ${name} — in Figma, has no id in tokens/config.mjs`);
for (const name of Object.keys(CATEGORY_IDS)) if (!figmaCategories.includes(name)) errors.push(`category ${name} — has an id in tokens/config.mjs, missing from Figma`);
const CATEGORIES = Object.entries(CATEGORY_IDS)
  .filter(([name]) => figmaCategories.includes(name))
  .map(([name, id]) => ({ id, name }))
  .sort((a, b) => a.id - b.id);

const SIGNAL_ROLES = [...new Set(Object.keys(LIGHT).filter((k) => k.startsWith("signal/")).map((k) => k.split("/")[1]))];

/* Type — one role per Figma text style. */
const ROLES = [];
for (const [style, t] of Object.entries(FIGMA["Text styles"] ?? {})) {
  const v = t.$value;
  const font = FONTS[v.fontFamily];
  if (!font) { errors.push(`text style "${style}" — font "${v.fontFamily}" has no fallback stack in tokens/config.mjs`); continue; }
  const px = v.fontSize?.value ?? v.fontSize;
  const lh = v.lineHeight;
  const leading = typeof lh === "number" ? lh
    : lh?.unit === "px" ? +(lh.value / px).toFixed(3)
    : lh?.unit === "%" ? lh.value / 100 : undefined;
  if (leading === undefined) errors.push(`text style "${style}" — line height ${JSON.stringify(lh)} is not unitless, px or %`);
  ROLES.push({ name: slug(style), px, size: rem(px), leading, weight: v.fontWeight, family: font.key });
}

/* Dimensions — spacing and radius in px. */
const DIMENSIONS = {};
for (const [k, t] of Object.entries(flatten(FIGMA["Dimensions"]))) {
  const [group, step] = k.split("/");
  (DIMENSIONS[group] ??= {})[step] = t.$value;
}
const DIM_PREFIX = { spacing: "space", radius: "corner" };   // avoids Tailwind's --spacing and shadcn's --radius-*

/* ---------------------------------------------------------------- */
/* tokens.css                                                        */
/* ---------------------------------------------------------------- */

const SUFFIXES = ["fill-light", "fill-dark", "bg-light", "bg-dark", "text-light", "text-dark"];
const byKind = (prefix) => Object.keys(P).filter((k) => k.startsWith(prefix));

const l1 = [
  "/* ── Layer 1 · primitives ──────────────────────────────────────",
  "   Raw values from Figma. Never reference these from a component —",
  "   always go through the semantic layer below. */",
  ":root {",
  "  /* neutral ramp — cream at the top, slate at the bottom */",
  ...byKind("neutral/").sort((a, b) => +a.split("/")[1] - +b.split("/")[1]).map((k) => `  ${cssName(k)}: ${P[k]};`),
  "",
  "  /* categories — fill and background, per theme */"
];
for (const c of CATEGORIES)
  for (const s of SUFFIXES) { const k = `category/${c.name}/${s}`; if (k in P) l1.push(`  ${cssName(k)}: ${P[k]};`); }
l1.push("", "  /* signals — the only colours that become words */");
for (const name of [...new Set(byKind("signal/").map((k) => k.split("/")[1]))].sort())
  for (const s of SUFFIXES) { const k = `signal/${name}/${s}`; if (k in P) l1.push(`  ${cssName(k)}: ${P[k]};`); }
l1.push("}");

const lt = [
  "/* ── Layer 1 · type and dimensions ─────────────────────────────",
  "   No theme: sizes do not change between light and dark, so these",
  "   appear once and never in the .dark block.",
  "",
  "   Named --type-* rather than --text-*, which is Tailwind v4's own",
  "   font-size namespace — colliding with it would silently redefine",
  "   utilities the app already uses. */",
  ":root {",
  "  /* families */",
  ...Object.values(FONTS).map((f) => `  --font-${f.key}: ${f.stack};`),
  ""
];
for (const r of ROLES) {
  lt.push(
    `  /* ${r.name} — ${r.px}px */`,
    `  --type-${r.name}-family: var(--font-${r.family});`,
    `  --type-${r.name}-size: ${r.size};`,
    `  --type-${r.name}-leading: ${r.leading};`,
    `  --type-${r.name}-weight: ${r.weight};`,
    `  --type-${r.name}: ${r.weight} ${r.size}/${r.leading} var(--font-${r.family});`,
    ""
  );
}
lt.push("  /* spacing and corners — rem, no theme */");
for (const [group, scale] of Object.entries(DIMENSIONS))
  for (const [step, px] of Object.entries(scale)) lt.push(`  --${DIM_PREFIX[group] ?? group}-${step}: ${rem(px)};`);
lt.push("}");

const GROUPS = [
  ["chrome — everything the app owns, no hue of its own",
    (t) => t.startsWith("surface/") || t.startsWith("border/") || t.startsWith("text/")],
  ["categories — the user's data, the loudest thing on screen", (t) => t.startsWith("category/")],
  ["signals — success and failure messages only, never a row chip", (t) => t.startsWith("signal/")]
];
function body(map) {
  const out = [];
  for (const [label, test] of GROUPS) {
    out.push(`  /* ${label} */`);
    for (const token of Object.keys(map).filter(test)) out.push(`  ${cssName(token)}: var(${cssName(map[token])});`);
    out.push("");
  }
  out.pop();
  return out;
}

const css = [
  BANNER,
  l1.join("\n"), "",
  lt.join("\n"), "",
  ["/* ── Layer 2 · semantic, light ─────────────────────────────────",
   "   What components use. Each one points at a primitive. */",
   ":root {", ...body(LIGHT), "}"].join("\n"), "",
  ["/* ── Layer 3 · semantic, dark ──────────────────────────────────",
   "   Identical token names, remapped. Nothing else in the app changes.",
   "   Scoped to .dark to match the @custom-variant in index.css. */",
   ".dark {", ...body(DARK), "}"].join("\n"), ""
].join("\n");

/* ---------------------------------------------------------------- */
/* shadcn bridge — optional                                          */
/* ---------------------------------------------------------------- */

for (const [k, v] of Object.entries(BRIDGE)) if (!(v in LIGHT)) errors.push(`shadcn bridge --${k} — points at ${v}, which Figma does not define`);

const bridge = [
  BANNER,
  "/* Points shadcn/ui's variables at the design system, so existing",
  "   components pick it up without being touched.",
  "",
  "   NOT imported by default — this changes how every screen looks.",
  "   To switch over, add to index.css after the tokens import:",
  "",
  '     @import "./styles/shadcn-bridge.css";',
  "",
  "   Both themes come along, because the tokens resolve per theme. */",
  "",
  ":root, .dark {",
  ...Object.entries(BRIDGE).map(([k, v]) => `  --${k}: var(${cssName(v)});`),
  "}",
  ""
].join("\n");

/* ---------------------------------------------------------------- */
/* categories.ts                                                     */
/* ---------------------------------------------------------------- */

const ts = `${BANNER}
/** A category stores its id, never a colour. Changing a colour in Figma
 *  updates every existing category automatically. */
export const CATEGORIES = ${JSON.stringify(CATEGORIES, null, 2)} as const;

export type CategoryColor = (typeof CATEGORIES)[number];
export type CategoryColorId = CategoryColor["id"];
export type CategoryColorName = CategoryColor["name"];
export type CategoryRole = "fill" | "bg";

export const isCategoryColorId = (v: unknown): v is CategoryColorId =>
  typeof v === "number" && CATEGORIES.some((c) => c.id === v);

/** Category.color currently holds a hex string. This resolves either an id
 *  (new) or a name (also fine), and returns null for a legacy hex so callers
 *  can fall back while the data migrates. */
export function resolveCategoryColor(
  value: string | number | null | undefined
): CategoryColor | null {
  if (typeof value === "number") return CATEGORIES.find((c) => c.id === value) ?? null;
  if (typeof value === "string") return CATEGORIES.find((c) => c.name === value) ?? null;
  return null;
}

/** The bridge from stored value to painted colour. Resolves per theme
 *  automatically, because the CSS variable does. */
export function categoryVar(
  value: string | number | null | undefined,
  role: CategoryRole = "fill"
): string | null {
  const c = resolveCategoryColor(value);
  return c ? \`var(--category-\${c.name}-\${role})\` : null;
}
`;

/* ---------------------------------------------------------------- */
/* Contrast guardrails                                               */
/* ---------------------------------------------------------------- */

function luminance(hx) {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hx.slice(i, i + 2), 16) / 255)
    .map((c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function contrast(a, b) {
  const [x, y] = [luminance(a), luminance(b)].sort((m, n) => n - m);
  return (x + 0.05) / (y + 0.05);
}

const checks = [];
for (const [theme, map] of [["light", LIGHT], ["dark", DARK]]) {
  const v = (t) => P[map[t]];
  const add = (label, a, b, min) => {
    if (!v(a) || !v(b)) { errors.push(`${theme} · ${label} — ${!v(a) ? a : b} is not defined`); return; }
    checks.push({ label: `${theme} · ${label}`, ratio: contrast(v(a), v(b)), min });
  };
  add("raised on ground", "surface/raised", "surface/ground", 1.2);
  add("sunken on raised", "surface/sunken", "surface/raised", 1.2);
  add("track on raised", "surface/track", "surface/raised", 1.2);
  add("primary text on ground", "text/primary", "surface/ground", 4.5);
  add("secondary text on raised", "text/secondary", "surface/raised", 4.5);
  add("muted text on ground", "text/muted", "surface/ground", 4.5);
  add("muted text on raised", "text/muted", "surface/raised", 4.5);
  for (const c of CATEGORIES) {
    add(`${c.name} bar on track`, `category/${c.name}/fill`, "surface/track", 3);
    add(`text on ${c.name} background`, "text/primary", `category/${c.name}/bg`, 4.5);
    /* A chip has to read as a chip on a card. Dark only for now: in light
     * mode the chips' colour carries them on the white card. */
    if (theme === "dark") add(`${c.name} chip on card`, `category/${c.name}/bg`, "surface/raised", 1.5);
  }
  for (const s of SIGNAL_ROLES) {
    add(`${s} text on ground`, `signal/${s}/text`, "surface/ground", 4.5);
    add(`${s} text on its background`, `signal/${s}/text`, `signal/${s}/bg`, 4.5);
  }
}
const failed = checks.filter((c) => c.ratio < c.min);

/* ---------------------------------------------------------------- */
/* Write, report                                                     */
/* ---------------------------------------------------------------- */

if (errors.length) {
  console.error("\ntokens/figma.json IS INCOMPLETE OR INCONSISTENT:");
  for (const e of errors) console.error("  " + e);
  process.exit(1);
}

for (const w of [
  write("src/styles/tokens.css", css),
  write("src/styles/shadcn-bridge.css", bridge),
  write("src/tokens/categories.ts", ts)
]) console.log("  wrote " + w);

const dims = Object.values(DIMENSIONS).reduce((n, s) => n + Object.keys(s).length, 0);
console.log(`  ${Object.keys(P).length} primitives, ${Object.keys(LIGHT).length} semantic tokens per theme, ${ROLES.length} text styles, ${dims} dimensions`);
console.log(`  ${checks.length - failed.length}/${checks.length} contrast checks pass`);

if (failed.length) {
  console.error("\nCONTRAST FAILED:");
  for (const f of failed) console.error(`  ${f.label} — ${f.ratio.toFixed(2)}, needs ${f.min}`);
  console.error("\nFix the colour in Figma, re-export, and run `npm run tokens` again.");
  process.exit(1);
}
