/* Generated by tokens/build.mjs from tokens/figma.json — do not edit by hand.
   Change the design in Figma, re-export, and run `npm run tokens`. */

/** A category stores its id, never a colour. Changing a colour in Figma
 *  updates every existing category automatically. */
export const CATEGORIES = [
  {
    "id": 0,
    "name": "poppy"
  },
  {
    "id": 1,
    "name": "ochre"
  },
  {
    "id": 2,
    "name": "olive"
  },
  {
    "id": 3,
    "name": "fern"
  },
  {
    "id": 4,
    "name": "jade"
  },
  {
    "id": 5,
    "name": "lagoon"
  },
  {
    "id": 6,
    "name": "azure"
  },
  {
    "id": 7,
    "name": "cobalt"
  },
  {
    "id": 8,
    "name": "iris"
  },
  {
    "id": 9,
    "name": "orchid"
  },
  {
    "id": 10,
    "name": "fuchsia"
  },
  {
    "id": 11,
    "name": "crimson"
  }
] as const;

export type CategoryColor = (typeof CATEGORIES)[number];
export type CategoryColorId = CategoryColor["id"];
export type CategoryColorName = CategoryColor["name"];
export type CategoryRole = "fill" | "bg";

export const isCategoryColorId = (v: unknown): v is CategoryColorId =>
  typeof v === "number" && CATEGORIES.some((c) => c.id === v);

/** Category.color currently holds a hex string. This resolves either an id
 *  (new) or a name (also fine), and returns null for a legacy hex so callers
 *  can fall back while the data migrates. */
export function resolveCategoryColor(
  value: string | number | null | undefined
): CategoryColor | null {
  if (typeof value === "number") return CATEGORIES.find((c) => c.id === value) ?? null;
  if (typeof value === "string") return CATEGORIES.find((c) => c.name === value) ?? null;
  return null;
}

/** The bridge from stored value to painted colour. Resolves per theme
 *  automatically, because the CSS variable does. */
export function categoryVar(
  value: string | number | null | undefined,
  role: CategoryRole = "fill"
): string | null {
  const c = resolveCategoryColor(value);
  return c ? `var(--category-${c.name}-${role})` : null;
}
