/* Generated by tokens/build.mjs — do not edit by hand.
   Change tokens/recipe.mjs and run `npm run tokens`. */

/** A category stores its id, never a colour. Retuning a hue in
 *  tokens/recipe.mjs updates every existing category automatically. */
export const CATEGORIES = [
  {
    "id": 0,
    "name": "poppy",
    "hue": 24,
    "tier": "bright"
  },
  {
    "id": 1,
    "name": "ochre",
    "hue": 66,
    "tier": "deep"
  },
  {
    "id": 2,
    "name": "olive",
    "hue": 102,
    "tier": "bright"
  },
  {
    "id": 3,
    "name": "fern",
    "hue": 135,
    "tier": "deep"
  },
  {
    "id": 4,
    "name": "jade",
    "hue": 165,
    "tier": "bright"
  },
  {
    "id": 5,
    "name": "lagoon",
    "hue": 198,
    "tier": "deep"
  },
  {
    "id": 6,
    "name": "azure",
    "hue": 234,
    "tier": "bright"
  },
  {
    "id": 7,
    "name": "cobalt",
    "hue": 258,
    "tier": "deep"
  },
  {
    "id": 8,
    "name": "iris",
    "hue": 288,
    "tier": "bright"
  },
  {
    "id": 9,
    "name": "orchid",
    "hue": 312,
    "tier": "deep"
  },
  {
    "id": 10,
    "name": "fuchsia",
    "hue": 333,
    "tier": "bright"
  },
  {
    "id": 11,
    "name": "crimson",
    "hue": 357,
    "tier": "deep"
  }
] as const;

export type CategoryColor = (typeof CATEGORIES)[number];
export type CategoryColorId = CategoryColor["id"];
export type CategoryColorName = CategoryColor["name"];
export type CategoryRole = "fill" | "bg";

export const isCategoryColorId = (v: unknown): v is CategoryColorId =>
  typeof v === "number" && CATEGORIES.some((c) => c.id === v);

/** Category.color currently holds a hex string. This resolves either an id
 *  (new) or a name (also fine), and returns null for a legacy hex so callers
 *  can fall back while the data migrates. */
export function resolveCategoryColor(
  value: string | number | null | undefined
): CategoryColor | null {
  if (typeof value === "number") return CATEGORIES.find((c) => c.id === value) ?? null;
  if (typeof value === "string") return CATEGORIES.find((c) => c.name === value) ?? null;
  return null;
}

/** The bridge from stored value to painted colour. Resolves per theme
 *  automatically, because the CSS variable does. */
export function categoryVar(
  value: string | number | null | undefined,
  role: CategoryRole = "fill"
): string | null {
  const c = resolveCategoryColor(value);
  return c ? `var(--category-${c.name}-${role})` : null;
}
